// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "users" ("id", "email", "password", "verified", "registered_at")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, registered_at
`

type CreateUserParams struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Password     string             `json:"password"`
	Verified     pgtype.Bool        `json:"verified"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

type CreateUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Verified,
		arg.RegisteredAt,
	)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.RegisteredAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, verified, registered_at FROM users
WHERE id =  $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Verified     pgtype.Bool        `json:"verified"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Verified,
		&i.RegisteredAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
  email = COALESCE($1, email),
  password = COALESCE($2, password),
  verified = COALESCE($3, verified)
WHERE id = sql.arg(id)
`

type UpdateUserParams struct {
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
	Verified pgtype.Bool `json:"verified"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.Email, arg.Password, arg.Verified)
	return err
}
