// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/ScMofeoluwa/GatherGo/internal/domain/user/entity"
	mock "github.com/stretchr/testify/mock"
)

// UserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type UserRepositoryInterface struct {
	mock.Mock
}

type UserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryInterface) EXPECT() *UserRepositoryInterface_Expecter {
	return &UserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserRepositoryInterface) Create(ctx context.Context, user *entity.CreateUser) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.CreateUser) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.CreateUser
func (_e *UserRepositoryInterface_Expecter) Create(ctx interface{}, user interface{}) *UserRepositoryInterface_Create_Call {
	return &UserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserRepositoryInterface_Create_Call) Run(run func(ctx context.Context, user *entity.CreateUser)) *UserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.CreateUser))
	})
	return _c
}

func (_c *UserRepositoryInterface_Create_Call) Return(_a0 error) *UserRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *entity.CreateUser) error) *UserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepositoryInterface) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryInterface_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepositoryInterface_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepositoryInterface_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserRepositoryInterface_GetByEmail_Call {
	return &UserRepositoryInterface_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserRepositoryInterface_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepositoryInterface_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepositoryInterface_GetByEmail_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryInterface_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryInterface_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *UserRepositoryInterface_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepositoryInterface) GetByID(ctx context.Context, id string) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepositoryInterface_Expecter) GetByID(ctx interface{}, id interface{}) *UserRepositoryInterface_GetByID_Call {
	return &UserRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserRepositoryInterface_GetByID_Call) Run(run func(ctx context.Context, id string)) *UserRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepositoryInterface_GetByID_Call) Return(_a0 *entity.User, _a1 error) *UserRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepositoryInterface_GetByID_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *UserRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *UserRepositoryInterface) Update(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *UserRepositoryInterface_Expecter) Update(ctx interface{}, user interface{}) *UserRepositoryInterface_Update_Call {
	return &UserRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *UserRepositoryInterface_Update_Call) Run(run func(ctx context.Context, user *entity.User)) *UserRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *UserRepositoryInterface_Update_Call) Return(_a0 error) *UserRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, *entity.User) error) *UserRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepositoryInterface creates a new instance of UserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryInterface {
	mock := &UserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
